src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Delete;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
#[UniqueEntity(fields: ['name_cat'], message: 'Cette catégorie existe déjà')]
#[ApiResource(
    operations:[
        new GetCollection(
            uriTemplate: '/categories',
            normalizationContext: ['groups' => 'category-read']
        ),
        new Get(
            uriTemplate: '/categories/{id}',
            normalizationContext: ['groups' => 'category-read']
        ),
        new Post(
            uriTemplate: '/categories',
            denormalizationContext: ['groups' => 'category-write', 'allow_extra_attributes' => false],
            normalizationContext: ['groups' => 'category-read']
        ),
        new Put(
            uriTemplate: '/categories/{id}',
            denormalizationContext: ['groups' => 'category-write', 'allow_extra_attributes' => false],
            normalizationContext: ['groups' => 'category-read']
        ),
        new Delete(
            uriTemplate: '/categories/{id}'
        )
    ]
)]
class Category extends Entity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['category-read'])]
    private ?int $id = null;

    #[ORM\Column(length: 50, unique: true)]
    #[Assert\NotBlank(message: 'Le nom ne peut pas être vide')]
    #[Assert\Length(min: 3, max: 50, minMessage: 'Min 3 caractères', maxMessage: 'Max 50 caractères')]
    #[Groups(['category-read', 'category-write'])]
    private ?string $name_cat = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message: 'La description ne peut pas être vide')]
    #[Groups(['category-read', 'category-write'])]
    private ?string $description_cat = null;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'categories')]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameCat(): ?string
    {
        return $this->name_cat;
    }

    public function setNameCat(string $name_cat): static
    {
        $this->name_cat = $name_cat;

        return $this;
    }

    public function getDescriptionCat(): ?string
    {
        return $this->description_cat;
    }

    public function setDescriptionCat(string $description_cat): static
    {
        $this->description_cat = $description_cat;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addCategory($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            $article->removeCategory($this);
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_cat', TextType::class, [
                'required' => false,
                'label' => 'Nom de la catégorie',
                'label_attr' => [
                    'class' => 'block text-lg font-medium mb-2',
                ],
                'required' => false,
                'attr' => [
                    'placeholder' => 'Ex. : Musique, Livres, Jeux vidéo',
                    'class' => 'input input-bordered w-full focus:outline-none focus:ring-2 focus:ring-primary',
                    'data-cy' => 'name_cat'
                ],
                'constraints' => [
                    new NotBlank(message: "Merci d'entrer un nom"),
                    new Length(min: 2, minMessage: 'Le nom doit contenir {{ limit }} caractères', max: 50),
                ],
            ])
            ->add('description_cat', TextareaType::class, [
                'required' => false,
                'label' => 'Description',
                'label_attr' => [
                    'class' => 'block text-lg font-medium mb-2',
                ],
                'attr' => [
                    'placeholder' => 'Décris brièvement cette catégorie...',
                    'rows' => 5,
                    'class' => 'textarea textarea-bordered w-full focus:outline-none focus:ring-2 focus:ring-primary',
                    'data-cy' => 'description_cat'
                ],
                'constraints' => [
                    new NotBlank(message: "Merci d'entrer une description"),
                    new Length(min: 2, minMessage: 'La description doit contenir {{ limit }} caractères'),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Service\CategoryService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;

#[Route('/category')]
final class CategoryController extends AbstractController
{
    public function __construct(
        private CategoryService $categoryService
    ) {}

    #[Route('/all', name: 'app_category_all')]
    public function categories(): Response
    {
        $categories = $this->categoryService->getAll();
        return $this->render('category/categories.html.twig', [
            'categories' => $categories,
        ]);
    }

    #[Route('/one/{id}', name: 'app_category_one')]
    public function category(int $id): Response
    {
        $category = $this->categoryService->getOne($id);
        return $this->render('category/category.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/add', name: 'app_category_add')]
    public function addCategory(Request $request): Response
    {
        $result = $this->categoryService->addCategory($request);

        if ($result['submitted'] && $result['valid']) {
            $this->addFlash('success', 'Catégorie ajoutée avec succès');
            $result['form'] = $this->categoryService->clearForm(CategoryType::class, new Category());
        }

        return $this->render('category/add.html.twig', [
            'categoryForm' => $result['form']
        ]);
    }
}

templates/category/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<turbo-frame id="category-form">
    {{ form_errors(categoryForm) }}
	{{ form(categoryForm) }}
		{% for message in app.flashes('success') %}
			<div class="alert alert-success">
				{{ message }}
			</div>
		{% endfor %}
</turbo-frame>
	{% endblock %}

templates/category/categories.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des catégories
{% endblock %}

{% block body %}
	<div class="min-h-screenmin-h-[calc(100vh-var(--navbar-height))] bg-base-200 py-10 px-4 sm:px-6 lg:px-8">
		<h1 class="text-4xl font-bold text-center mb-10 text-primary">Nos Catégories</h1>
		<p class="text-2xl font-bold text-center mb-10"><a href="{{ path('app_category_add') }}">Créer une catégorie</a></p>

		<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
			{% for category in categories %}
				<div class="card bg-base-100 shadow-xl hover:shadow-2xl transition-shadow duration-300 rounded-lg overflow-hidden">
					<div
						class="card-body p-6 flex flex-col items-center text-center">
						<!-- Category name -->
						<h2 class="text-xl font-semibold mb-2">{{ category.nameCat }}</h2>

						<!-- Action button -->
						<div class="card-actions">
							<a href="{{ path('app_category_one', {id: category.id}) }}" class="btn btn-sm btn-primary">Voir Détails</a>
						</div>
					</div>
				</div>
			{% else %}
				<p class="col-span-full text-center text-gray-400 mt-10">Aucune catégorie trouvée.</p>
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/category/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégorie :
	{{ category.nameCat }}
{% endblock %}

{% block body %}
	<div class="min-h-[calc(100vh-var(--navbar-height))] bg-base-200 flex items-center justify-center py-10 px-4 sm:px-6 lg:px-8">
		<div class="card w-full max-w-md bg-base-100 shadow-2xl rounded-xl overflow-hidden">
			<div
				class="card-body items-center text-center p-8">
				<!-- Name -->
				<h2 class="text-2xl font-bold mb-2">{{ category.nameCat }}</h2>

				<!-- Description -->
				<p class="text-gray-500 mb-4">{{ category.descriptionCat }}</p>

				<!-- Actions -->
				<div class="card-actions justify-center gap-4">
					<a href="{{ path('app_category_all') }}" class="btn btn-sm btn-primary">Retour à la liste</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}